version: '3.9'
services:
  mongo:
    image: mongo:6
    ports: ["27017:27017"]
    volumes: ["mongo_data:/data/db"]
  mongo-express:
    image: mongo-express:1.0.2-20
    ports: ["8081:8081"]
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on: [mongo]
volumes:
  mongo_data:
