name: CI
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [api, web]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: |
          cd ${{ matrix.dir }}
          npm ci
      - name: Build
        run: |
          cd ${{ matrix.dir }}
          npm run build || true
      - name: Test
        if: matrix.dir == 'api'
        run: |
          cd api
          npm test -- --run
